config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "lists#home"

  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      redirect_to list_path(@list), status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def home
  end

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_content
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fa-solid fa-film"></i>  WatchList  <i class="fa-solid fa-film"></i>
  </div>
</div>

app/views/lists/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.vecteezy.com/system/resources/previews/010/852/520/non_2x/cinema-entertainment-banner-vector.jpg);">
  <div class="container text-align-right">
    <h1><strong><%= link_to "WatchList", lists_path, class: "btn btn-flat fs-1", style: "margin-left: 900px;" %></strong></h1>
  </div>
</div>
<%= render "footer" %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.vecteezy.com/system/resources/previews/010/852/520/non_2x/cinema-entertainment-banner-vector.jpg);">
  <div class="container text-align-right">
    <h1><strong><%= link_to "Add a list", new_list_path, class: "btn btn-flat fs-1", style: "margin-left: 900px;" %></strong></h1>
  </div>
</div>

<div class="container justify-content-start">
  <div class="d-flex mt-5 align-items-center justify-content-between">
    <h2 class="display-6 "><strong>Your lists</strong></h2>
    <%= link_to "Back", root_path, class: "btn btn-outline-danger" %>
  </div>
  <% @lists.each do |list| %>
    <div class="card-trip mt-5">
      <div class="card-trip-infos">
        <h3><%= link_to list.name, list_path(list.id), class: "text-decoration-none" %></h3>
      </div>
    </div>
  <% end %>
</div>
<%= render "footer" %>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.vecteezy.com/system/resources/previews/010/852/520/non_2x/cinema-entertainment-banner-vector.jpg);">
  <div class="container text-align-right">
    <h1 class="display-1 fs-1", style="margin-left: 900px;"><strong>Add a list</strong></h1>
  </div>
</div>

<div class="container mt-3">
  <%= simple_form_for [@list] do |f| %>
    <%= f.input :name, label: false, class: "display-3", placeholder: "Your new list name" %>
    <%= f.submit %>
  <% end %>
  <%= link_to "Back", lists_path, class: "btn btn-outline-danger mt-3" %>
</div>
<%= render "footer" %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.vecteezy.com/system/resources/previews/010/852/520/non_2x/cinema-entertainment-banner-vector.jpg);">
  <div class="container text-align-right">
    <h1 class="display-1 fs-1", style="margin-left: 900px;"><strong> <%= @list.name %></strong></h1>
  </div>
</div>
<div class="container">
  <div class="d-flex justify-content-between mt-3">
    <div class="align-content-center">
      <%= link_to "Back", lists_path, class: "btn btn-outline-danger" %>
    </div>
  </div>
    <% @list.bookmarks.each do |bookmark| %>
        <div class="card-product mt-3">
          <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title %>
          <div class="card-product-infos">
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.movie.overview %></p>
            <strong><%= bookmark.movie.rating %>/10</strong>
            <p><i>"<%= bookmark.comment %>"</i></p>
          </div>
      </div>
        <%= link_to "Delete", bookmark_path(bookmark),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class: "btn btn-outline-danger"%>
    <% end %>
    <div class="mt-3">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, collection: Movie.all, prompt: "Choose a film", label: false %>
          <%= f.input :comment, label: false, placeholder: "Your comment about this movie..." %>
          <%= f.button :submit, "Add this film", class: "btn btn-outline-primary" %>
        <% end %>
    </div>
  </div>
</div>
<%= render "footer" %>